typedef sequence<string> stringTable;

interface LinkExchangeSystem {
  void register( in string username, out long userID );
  void addLink( in long userID, in string link, out long linkID );
  boolean linkRemove( in long userID, in long linkID );
  boolean publishLink( in long userID, in long linkID );
  long getLinks( in long userID, out stringTable links );
};


